### ISSUE TITLE
wrong version number in Grisbi 1.2.1 for MacOS

### ISSUE THREAD

**Issue by suschizu** [grisbi/grisbi-documentation#4]
Hello!
sorry for posting this issue in the documentation - but I haven't found another place to write a bug report for Grisbi …  
The latest download of Grispi still shows 1.0.0 as version (I downloaded v1.2.1 from sourceforge) 
![Screenshot 2019-04-10 at 17 35 42](https://user-images.githubusercontent.com/16004333/55893011-b4161680-5bb7-11e9-92b5-7c21710c1664.png)

**Comment by LudovicRousseau** [comment]
The URL to report bugs is indicated as the bottom of the project web page http://en.grisbi.org/
It is http://www.grisbi.org/bugsreports/

You are right. The version indicated is still 1.0.0. I will try to fix that.

**Comment by LudovicRousseau** [comment]
Fixed in https://github.com/grisbi/grisbi/commit/6f5f15ab813f47bae8f508c5980a1ccf5449f83e

**Comment by suschizu** [comment]
sorry - I was looking on the wrong place
merci beaucoup!
