### ISSUE TITLE
Website seems down

### ISSUE THREAD

**Issue by redtux** [grisbi/grisbi-documentation#5]
Hi, thank you for taking up the development again! I just want to propose redirecting grisbi.org to the GitHub repo or to https://sourceforge.net/projects/grisbi/files/Documentation/manual_1.0/ - otherwise one might think that this project is dead. Keep up the good work!

**Comment by LudovicRousseau** [comment]
Hello,
Why do you have the impression that https://grisbi.org/ is dead?

A better URL for the documentation is http://grisbi.sourceforge.net/html/ or http://grisbi.sourceforge.net/html-en/ for the English version.
See https://github.com/grisbi/grisbi/wiki

**Comment by redtux** [comment]
Hi, just because the last stable release on SF is quite old (development seems to happen in the unstable branch for years), because there is no package for Debian or Ubuntu, and because of the website, that says "Dotclear: Blog is not defined. Did you change your Blog ID?" Anyway, good to see I was wrong! Thank you for the links! 👍

**Comment by LudovicRousseau** [comment]
- The latest stable version 1.2.2 is from April 2019, less than 2 years ago.
- Ubuntu and Debian packages are available in the respective distributions
  - https://packages.debian.org/grisbi
  - https://packages.ubuntu.com/grisbi

Were do you find "Dotclear: Blog is not defined. Did you change your Blog ID?" in the website? I cant' find it.

**Comment by redtux** [comment]
Oh, this seems to be an issue with [Firefox Klar](https://f-droid.org/en/packages/org.mozilla.klar/). :rofl: 
Sorry for not having checked with another browser. :facepalm: 
Happy new year and thank you for your help! :+1:
