### ISSUE TITLE
Migrate website to GitHub Pages?

### ISSUE THREAD

**Issue by spoelstraethan** [grisbi/grisbi-documentation#6]
It appears the site isn't updated very frequently but has information about the 2.0.0 release, but also mentions an "upcoming 1.0" on the main page.

![image](https://user-images.githubusercontent.com/56567427/129784628-1b9d3e49-fff2-4546-ae77-437e27249a64.png)

**Comment by LudovicRousseau** [comment]
Exact. The English version of the web site needs some update.
Thanks for the notice.

**Comment by LudovicRousseau** [comment]
Fixed.
